### ISSUE TITLE
Zero spectrum input 

### ISSUE THREAD

**Issue by gdhungana** [desihub/specsim#1]
returns zero flux and zero ivar for input zero spectrum. This is particularly needed the case in sky spectrum. Should have some variance even for zero input.

**Comment by dkirkby** [comment]
The reason for ivar=0 where flux=0 is that ivar of the coadd is calculated as (snr/flux)**2, so fixing this issue involves revisiting how the coadd is calculated.  I will create a new issue for that.

In the meantime, I created a new unit test that will fail until this issue is fixed.

**Comment by dkirkby** [comment]
Fixed by #35
