### ISSUE TITLE
Deprecated astropy function arguments

### ISSUE THREAD

**Issue by JiachuanXu** [desihub/specsim#133]
TypeError: HDUList.writeto() got an unexpected keyword argument 'clobber'

https://github.com/desihub/specsim/blob/238d0b89e0dbda180d6ced8ae2fd013a823b03de/specsim/fiberloss.py#L274C57-L274C57

deprecated arguments `clobber` in `HDUList.writeto()`, now replaced with `overwrite`; can not save fiberloss table now.

**Comment by weaverba137** [comment]
Fixed in #132.
