### ISSUE TITLE
Use other packages for generic re-usable operations

### ISSUE THREAD

**Issue by dkirkby** [desihub/specsim#16]
There are several generic operations implemented in this package that are not simulation specific, and potentially useful as independent re-usable components:
* interpolation of input tabulated functions (source SED, sky background, extinction, etc) to the simulation wavelength grid.
* downsampling of simulated results from the high-resolution internal wavelength grid to the output grid.
* weighted stacking of the per-camera predictions to simulate a coadd.
* redshifting an SED.
* renormalizing an SED to a specified magnitude in a specified pass band.

The first 4 of these are already implemented in the [speclite package](http://speclite.readthedocs.org/en/latest/overview.html), which was partly created with this migration in mind. The last item involves one of the following:
* moving the filter definitions and synthetic magnitude calculation into `speclite`.
* using an existing package that already does synthetic magnitude calculations.

Using an existing package is preferable as long as it does not introduce any additional dependencies or restrict the versions of python, numpy, etc, that are supported by `desisim`.  Are there any candidates?

**Comment by moustakas** [comment]
I poked around about 6 months ago looking for a package that did filter convolutions and didn't find anything light-weight.  The only thing I found was some stuff in astLib.astSED, which I shamelessly stole and put into a simple class in desisim.filterfunc

+1 for having this functionality in speclite, but note that desispec would then depend on speclite (to do the flux-calibration), but I guess it would depend on speclite for a lot of other functionality if we move in this direction (which I'm all for).

**Comment by dkirkby** [comment]
Now that speclite v0.3 includes the necessary filter operations, I am starting a new branch for the migration.

**Comment by dkirkby** [comment]
Fixed by PR #29
