### ISSUE TITLE
simplify extracting resolution matrix from simulator

### ISSUE THREAD

**Issue by sbailey** [desihub/specsim#18]
The high-resolution "resolution matrix" that convolves the source spectrum by the instrumental resolution is available as `qsim.cameras[j].sparseKernel`.  It would be handy if the user could access the binned equivalent after downsampling, i.e. the resolution matrix corresponding to the output flux.  I think we would want it to have the property that
```
result = qsim.simulate(..., downsampling=n)
R = qsim.get_binned_resolution(..., downsampling=n)
np.all(result.obsflux == R.dot(result.srcflux))
```
Or at least as close to that as is possible given the rebinning.

**Comment by dkirkby** [comment]
Fixed by #35
