### ISSUE TITLE
Document installation of desimodel data files

### ISSUE THREAD

**Issue by dkirkby** [desihub/specsim#41]
The instructions [here](http://specsim.readthedocs.io/en/stable/config.html#desi-configuration) should be augmented with the specific steps needed to checkout the desimodel package from svn.  Also, the desimodel link should point to the svn repo instead of the github repo.

**Comment by dkirkby** [comment]
I think this should work for any user (without special DESI privileges):
```
svn co https://desi.lbl.gov/svn/code/desimodel/trunk desimodel
```
Next, configure the DESIMODEL environment variable.  This step is OS and shell specific, but for unix/mac and bash:
```
cd desimodel
export DESIMODEL=`pwd`
```
Please post corrections / improvements here.

**Comment by dkirkby** [comment]
@weaverba137 Any corrections or improvements to suggest for this documentation update?

**Comment by weaverba137** [comment]
I'm not sure why this is a specsim issue & not a desimodel issue.  I think the install instructions in desimodel's top-level README.rst file are complete.

**Comment by dkirkby** [comment]
The reason is that someone starting with `specsim` wouldn't know to look at the `desimodel` docs, but that README has all the relevant info so I will just point to it.
