### ISSUE TITLE
Add option to bypass any resolution-convolved calculations

### ISSUE THREAD

**Issue by dkirkby** [desihub/specsim#66]
This could be useful when specsim is calculating photons input to a 2D sensor simulation, i.e., specsim handles the atmosphere model and fiberloss calculations, and provides high resolution arrays of source and sky photons entering the instrument.  Specifically, this mode would only provide the `simulated` output table and not the per-camera output tables (see [here](http://specsim.readthedocs.io/en/stable/output.html) for details).

This should reduce the memory footprint and run time, which (I suspect) are both dominated by the per-camera resolution matrix and convolutions. This mode would be selected with an optional arg to the `Simulator` ctor, e.g.
```
desi = specsim.simulator.Simulator('desi', num_fibers=5000, camera_output=False)
```

**Comment by dkirkby** [comment]
@sbailey writes that in addition to the `Simulator.simulated` table, he needs:
- [ ] `Simulator.camera_names`
- [ ] `Simulator.camera_output[i]['wavelength']`

I need to check on these...

**Comment by sbailey** [comment]
`Simulator.camera_names` : it would be handy to retain this, but I don't mind hardcoding around it if needed.  I suspect the same information is also available via the `Configuration` object (pointers welcome).  I'm just being careful in using `Simulator.camera_names[i]` in parallel with `Simulator.camera_output[i]` in case the order every changes from `['b', 'r', 'z']`.

`Simulator.camera_output[i]['wavelength']`  I only use the first and last elements to get the wavelength ranges that are valid for the `Simulator.simulated['num_source_electrons_*']` per-camera columns.  If the min/max wavelength ranges for each camera are kept elsewhere within the `Simulator` or `Configuration` object I could grab from there instead.  I could also get the ranges via desimodel if needed.

**Comment by dkirkby** [comment]
> I'm just being careful in using Simulator.camera_names[i] in parallel with
> Simulator.camera_output[i] in case the order every changes from ['b', 'r', 'z'].

Everywhere cameras are listed, they are always in order of increasing effective wavelength.

**Comment by dkirkby** [comment]
> I only use the first and last elements to get the wavelength ranges that are valid for the 
> Simulator.simulated['num_source_electrons_*'] per-camera columns

I suspect the per-camera `wavelength_min/max` [attributes](
http://specsim.readthedocs.io/en/stable/api/specsim.camera.Camera.html#specsim.camera.Camera.wavelength_max) will do the job here.  The Camera objects are still accessible via the list `simulator.instrument.cameras` in this new mode.
