### ISSUE TITLE
Error when installing specsim on edison

### ISSUE THREAD

**Issue by weaverba137** [desihub/specsim#69]
While installing specsim on edison, I got the following error:
```
desi@edison06[1092]$ desiInstall -d specsim v0.9
desiInstall [desiutil.install.DesiInstall.get_options] Log - WARNING: The environment variable LANG is not set!
desiInstall [desiutil.install.DesiInstall.install] Log - CRITICAL: Error during installation: fc-list: unrecognized option '--format=%{file}'
usage: fc-list [-vV?] [--verbose] [--version] [--help] [pattern] {element ...} 
List fonts matching [pattern]
  -v, --verbose        display status information while busy
  -V, --version        display font config version and exit
  -?, --help           display this help and exit
```
I think this error is actually an "afterburner" and that the package is still installed more-or-less properly, but it would be good to understand what's going on so that specsim can continue to be installed by desiInstall.

**Comment by dkirkby** [comment]
I haven't used `desiInstall` before.  Did this work with earlier tags on edison, or does it still work on other platforms?

**Comment by sbailey** [comment]
desiInstall has previously successfully installed specsim at NERSC; I have a vague memory of seeing this message before, but empirically the install worked so I moved on.  Bonus points to Ben for taking the time to reporting it.

**Comment by sbailey** [comment]
perhaps related: I have also seen messages about rebuilding the font-cache while using installed specsim at NERSC.  This has happened multiple times even for the same install, but doesn't seem to happen everytime.  Perhaps once per different login node?  I never tracked which piece of code was causing it (perhaps not even specsim), but perhaps it is related to fonts not being fully configured at install time.

**Comment by sbailey** [comment]
More craziness with same error but unrelated to specsim:
```
[edison12 ~] module use /global/common/$NERSC_HOST/contrib/desi/modulefiles
[edison12 ~] module load desiconda
[edison12 ~] module unload desitarget
[edison12 ~] module load desiutil
[edison12 ~] python -c "import healpy"
fc-list: unrecognized option '--format=%{file}'
usage: fc-list [-vV?] [--verbose] [--version] [--help] [pattern] {element ...} 
List fonts matching [pattern]

  -v, --verbose        display status information while busy
  -V, --version        display font config version and exit
  -?, --help           display this help and exit
[edison12 ~] which python
/global/common/edison/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/bin/python
```
Logging out and logging back in to the same node and repeating the commands did not reproduce the problem.  Cutting and pasting history here for the record...

**Comment by weaverba137** [comment]
I recall that fc-list is usually associated with importing matplotlib.

**Comment by dkirkby** [comment]
`rebuilding the font-cache` is also associated with matplotlib (but normally only occurs the first time you use it).

However, installing specsim should not pull in matplotlib.

**Comment by dkirkby** [comment]
@weaverba137 Can you close this if you think it is resolved?

**Comment by weaverba137** [comment]
I did not see this error with release 18.6, so let's close this and create a new issue if it ever pops up again.
