### ISSUE TITLE
specsim and pixsim do not agree exactly

### ISSUE THREAD

**Issue by dkirkby** [desihub/specsim#7]
This problem was reported by Ryan Staten.

The next step is to make sure we agree on the output of the following quicksim calculation:
```
python bin/quicksim.py --infile data/spectra/spec-ABmag22.0.dat --model qso --verbose --outfile ab22.dat
```
then to compare with the equivalent pixsim output.

**Comment by rstaten** [comment]
I run the following command and get the following error. Quicksim output is fine.

python pixsim.py --infile data/spectra/spec-ABmag22.0.dat --model qso --verbose --outfile ab22_pix.dat

File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by dkirkby** [comment]
I didn't mean that the pixsim command line should be identical but perhaps it has the same options as quicksim?  I just wanted you to run with the same input spectrum (an ideal 22nd AB-magnitude source) so we can make some direct comparisons.  Hopefully @sbailey can help interpret this error.

**Comment by gdhungana** [comment]
Hi @dkirkby ; @rstaten , yes we can set identical inputs, in this case, same input spectrum, objtype, airmass, exptime, sky etc. pixsim and quicksim mostly have the same default values, if not all. I'll check this tomorrow and update the output form each.  But it looks like the quicksim wrapper writes to the output file most of the results from simulation. Are the wavelengths, counts (obj+sky) and inverse variance form pixsim sufficient for your comparison? To get sky, or calibrated flux as in quicksim case, we have to pass further downstream in the pipeline.

**Comment by gdhungana** [comment]
@rstaten Pixsim can take the same input spectrum but not in the identical format as for bin/quicksim.py. The existing pixsim wrapper takes the 'simspec' file, which is not the case here. You have to pass the single spectrum into the simulator, and save the output for comparison.

**Comment by dkirkby** [comment]
> Are the wavelengths, counts (obj+sky) and inverse variance form pixsim sufficient for your comparison?

@gdhungana That should be enough to get started, at least.

**Comment by rstaten** [comment]
Hi @dkirkby<https://github.com/dkirkby> ; @gdhungana<https://github.com/gdhungana>, sorry, I misinterpreted and thought you wanted me to provide that exact command. As Govinda said, we can input the same spectrum and the data I sent out recently describing differences between the two simulations and simspec is based on using the same input. In general, for me at least, inverse variance and wavelengths seem fine between the two simulations with respect to bin size, it's just the counts that are off.

dkirkby · GitHub
dkirkby has 9 repositories written in Python, JavaScript, and Ruby. Follow their code on GitHub.
Read more...<https://github.com/dkirkby>




________________________________

**Comment by dkirkby** [comment]
@rstaten The purpose of the test I proposed is to establish a simple benchmark comparison using a single smooth spectrum, in order to investigate the problem further.

**Comment by sbailey** [comment]
A bit of context.  `pixsim-desi.py` itself doesn't do the throughput calculation; it relies upon `newexp-desi.py` to collect up templates and generate simspec files for pixsim to use as input.  simspec includes both the flux-calibrated [erg/s/cm2/A] truth from the templates, and the raw photon truth that should be coming out of the post-pixsim extractions.

The relevant bits for doing the ABmag22 comparison that David proposed are:
```
import desimodel.io
thru = desimodel.io.load_throughput('b')  #- or 'r' or 'z', requires specter under the hood
photons = thru.photons(wave, flux, units='ergs/s/cm2/A', objtype='STAR', exptime=1000, airmass=1.0)
```

output is photons per bin, not photons per Angstrom.  For comparison with specsim, make sure you are using the same objtype, exptime, and airmass.

**Comment by gdhungana** [comment]
Hi Stephen, all.

Indeed. Though the units should have 1e-17 in front, or may be use a normalization factor? But here is an example run that I did using 'b' channel. I explicitly did the projection to CCD part and wrote to a file. Then I used extraction wrapper 'exspec' to do the extraction. I can do ex2d explicitly but that shouldn't make any difference. Please let me know if I made any different than that should go to simspec file. Of course, simspec file has more info.

import desimodel.io
import numpy as np
import os
from desisim.pixsim import parallel_project
from desispec.image import Image
import desispec.io
import astropy.io.fits as fits


thru = desimodel.io.load_throughput('b')
specfile=os.getenv('DESIMODEL')+'/data/spectra/spec-ABmag22.0.dat'
wave,flux=np.loadtxt(specfile,unpack=True)
photons = thru.photons(wave, flux, units='1e-17 erg/s/cm2/A', objtype='QSO', exptime=1000, airmass=1.0)

skyfile = os.getenv('DESIMODEL')+'/data/spectra/spec-sky.dat'
skywave, skyflux = np.loadtxt(skyfile, unpack=True)
skyflux = np.interp(wave, skywave, skyflux)
skyphot = thru.photons(wave, skyflux*1.0, units='1e-17 erg/s/cm2/A/arcsec2', objtype='SKY', exptime=1000, airmass=1.0)

phot=photons+skyphot
phot=phot.reshape(1,phot.shape[0])

psf = desimodel.io.load_psf('b')
img = parallel_project(psf, wave, phot)
params = desimodel.io.load_desiparams()
nfibers = params['spectro']['nfibers']
readnoise = params['ccd']['b']['readnoise']

pix = np.random.poisson(img) + np.random.normal(scale=readnoise, size=img.shape)
ivar = 1.0/(pix.clip(0) + readnoise**2)
piximage=Image(pix,ivar)
desispec.io.write_image('pix_check.fits',piximage)

####From here I ran the following command from the terminal to do the extraction. Sending the file ####in email. Don't know if I can upload here! 
$ exspec -i 'pix_check.fits' -o 'ABmag22.0_b_extract.fits' -p '/home/govinda/Desi/desimodel/data/specpsf/psf-b.fits'  --specrange 0,1 -w 3570,5940,0.5

**Comment by gdhungana** [comment]
Forgot to mention, that the atmospheric extinction has been decoupled for sky in pixsim also (specter.throughput) to make the overall throughput same as quicksim.

**Comment by dkirkby** [comment]
I am closing this issue since the discrepancies are due to different ways of calculating the number of detected electrons per angstrom, resulting from numerical implementation details such as different interpolation schemes.  These differences are well below the accuracy of these calculations and will disappear when we move to using the same code for these calculations in both simulators.
