### ISSUE TITLE
travis tests

### ISSUE THREAD

**Issue by tolgayapici** [desihub/specsim#74]
as i was looking at the failure messages on travis tests, I realize that none of the tests for testing different versions of numpy actually uses the version in the config file.
for a similar reason, in the dithering branch and in my pull request, one of the tests is failing because numpy version 1.13 only works for Python version 2.7 or >= 3.4.

**Comment by dkirkby** [comment]
@tolgayapici Can you give a bit more detail on the issue here?  If I look at this [recent travis log](https://api.travis-ci.org/v3/job/408560710/log.txt) which is configured to use numpy 1.10, I see, for example:
```
$ export NUMPY_VERSION=1.10
...
The following NEW packages will be INSTALLED:

    mkl:   11.3.3-0     
    numpy: 1.10.4-py35_2
...
Numpy: 1.10.4
...
```
It looks like the test is using the specified version.

**Comment by weaverba137** [comment]
Aside from determining which numpy version is being tested, hopefully at least some tests are using 1.13 & 1.14.  1.10 is getting old at this point.

**Comment by dkirkby** [comment]
We are [currently testing](https://github.com/desihub/specsim/blob/master/.travis.yml) numpy 1.10, 1.11, 1.12 and "prerelease".  I agree this should be updated but that's a separate issue, so I am closing this now.
