### ISSUE TITLE
notebook example broken?

### ISSUE THREAD

**Issue by ngbusca** [desihub/specsim#86]

**Comment by ngbusca** [comment]
I'm trying to run the notebook example SimulationExamples. When running the config step:

    desi = specsim.simulator.Simulator('desi', num_fibers=500)

I get an error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-b8bbe59dd2d6> in <module>()
----> 1 desi = specsim.simulator.Simulator('desi', num_fibers=500)

/Users/ngbusca/anaconda2/lib/python2.7/site-packages/specsim-0.12.dev764-py2.7.egg/specsim/simulator.pyc in __init__(self, config, num_fibers, camera_output, verbose)
     73         # Initalize our component models.
     74         self.atmosphere = specsim.atmosphere.initialize(config)
---> 75         self.instrument = specsim.instrument.initialize(config, camera_output)
     76         self.source = specsim.source.initialize(config)
     77         self.observation = specsim.observation.initialize(config)

/Users/ngbusca/anaconda2/lib/python2.7/site-packages/specsim-0.12.dev764-py2.7.egg/specsim/instrument.pyc in initialize(config, camera_output)
    669             raise RuntimeError(
    670             'Cannot find file {}. May need to update desimodel svn ?'
--> 671             .format(filename))
    672         fast_fiber_acceptance = specsim.fastfiberacceptance.FastFiberAcceptance(
    673             filename)

RuntimeError: Cannot find file /Users/ngbusca/Boulot/DESI/desimodel/data/throughput/galsim-fiber-acceptance.fits. May need to update desimodel svn ?

**Comment by ngbusca** [comment]
Indeed, the file galsim-fiber-acceptance.fits is missing... is it supposed to be shipped with specsim or should I get it from somewhere else?

**Comment by sbailey** [comment]
Yes, indeed, update desimodel svn to get `data/throughput/galsim-fiber-acceptance.fits`, which was added last October at the time of specsim PR #81.

**Comment by ngbusca** [comment]
Yep, svn update in $DATAMODEL fixed it! Thanks @sbailey
